[build]
builder = "heroku/builder:22"

[phases.build]
cmds = [
  "chmod -R 775 /app/storage /app/bootstrap/cache",
  "chown -R www-data:www-data /app/storage /app/bootstrap/cache",
  "composer install --optimize-autoloader --no-dev",
  "php artisan optimize:clear"
]

[start]
cmd = "php-fpm -D && nginx -g 'daemon off;'"

[nginx]
port = 8080
root = "/app/public"

[nginx.locations]
"~ \.php$" = '''
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    fastcgi_buffer_size 8k;
    fastcgi_buffers 16 16k;
    fastcgi_param SCRIPT_FILENAME $realpath_root/$fastcgi_script_name;
    include fastcgi_params;
    include fastcgi.conf;
'''

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://your-domain.com"
APP_KEY = "base64:paste_your_generated_key_here"

# Optional env vars (define in Coolify UI or uncomment here)
# POSTMARK_MESSAGE_STREAM_ID = ""
# MAIL_LOG_CHANNEL = ""
# AWS_ACCESS_KEY_ID = ""
# AWS_SECRET_ACCESS_KEY = ""
# SLACK_BOT_USER_OAUTH_TOKEN = ""
